name: GitHub Actions file health check

on:
  push:
    branches: [ '**' ]
  pull_request:
    types: [edited, opened, reopened, synchronize]
    branches: [ '**' ]

jobs:
  check_file_health:
    name: Check file health

<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    runs-on: ubuntu-20.04
>>>>>>> 3485ad39d9729e9ca106191b0e02719b46f5cfd8

    steps:
    - name: checkout repository
      uses: actions/checkout@v2

    - name: install zsh
      run: |
        sudo apt update
        sudo apt install zsh

    - name: run check file health script
      run: |
        ./.github/workflows/file_health.sh
